var searchData=
[
  ['dataorblockpointer_8563',['DataOrBlockPointer',['../unionDGtal_1_1LabelledMap_1_1DataOrBlockPointer.html',1,'DGtal::LabelledMap']]],
  ['decoratorparametriccurvetransformation_8564',['DecoratorParametricCurveTransformation',['../classDGtal_1_1DecoratorParametricCurveTransformation.html',1,'DGtal']]],
  ['defaultcellmapiteratorpriority_8565',['DefaultCellMapIteratorPriority',['../structDGtal_1_1CubicalComplex_1_1DefaultCellMapIteratorPriority.html',1,'DGtal::CubicalComplex']]],
  ['defaultconstimagerange_8566',['DefaultConstImageRange',['../classDGtal_1_1DefaultConstImageRange.html',1,'DGtal']]],
  ['defaultconstructible_8567',['DefaultConstructible',['../structboost_1_1DefaultConstructible.html',1,'boost']]],
  ['defaultconstructible_3c_20s_20_3e_8568',['DefaultConstructible&lt; S &gt;',['../structboost_1_1DefaultConstructible.html',1,'boost']]],
  ['defaultimagerange_8569',['DefaultImageRange',['../classDGtal_1_1DefaultImageRange.html',1,'DGtal']]],
  ['delaunayintegralkernel_8570',['DelaunayIntegralKernel',['../structDGtal_1_1DelaunayIntegralKernel.html',1,'DGtal']]],
  ['delaunayrationalkernel_8571',['DelaunayRationalKernel',['../structDGtal_1_1DelaunayRationalKernel.html',1,'DGtal']]],
  ['depthfirstvisitor_8572',['DepthFirstVisitor',['../classDGtal_1_1DepthFirstVisitor.html',1,'DGtal']]],
  ['derivativetester_8573',['DerivativeTester',['../structDerivativeTester.html',1,'']]],
  ['derivativetester_3c_20calculus_2c_20_2d1_20_3e_8574',['DerivativeTester&lt; Calculus, -1 &gt;',['../structDerivativeTester_3_01Calculus_00_01-1_01_4.html',1,'']]],
  ['dicomreader_8575',['DicomReader',['../structDGtal_1_1DicomReader.html',1,'DGtal']]],
  ['digitalconvexity_8576',['DigitalConvexity',['../classDGtal_1_1DigitalConvexity.html',1,'DGtal']]],
  ['digitalconvexity_3c_20kspace_20_3e_8577',['DigitalConvexity&lt; KSpace &gt;',['../classDGtal_1_1DigitalConvexity.html',1,'DGtal']]],
  ['digitalmetricadapter_8578',['DigitalMetricAdapter',['../classDGtal_1_1DigitalMetricAdapter.html',1,'DGtal']]],
  ['digitalplanepredicate_8579',['DigitalPlanePredicate',['../classDGtal_1_1DigitalPlanePredicate.html',1,'DGtal']]],
  ['digitalsetboundary_8580',['DigitalSetBoundary',['../classDGtal_1_1DigitalSetBoundary.html',1,'DGtal']]],
  ['digitalsetbyassociativecontainer_8581',['DigitalSetByAssociativeContainer',['../classDGtal_1_1DigitalSetByAssociativeContainer.html',1,'DGtal']]],
  ['digitalsetbyassociativecontainer_3c_20dgtal_3a_3az3i_3a_3adomain_2c_20std_3a_3aunordered_5fset_3c_20typename_20dgtal_3a_3az3i_3a_3adomain_3a_3apoint_20_3e_20_3e_8582',['DigitalSetByAssociativeContainer&lt; DGtal::Z3i::Domain, std::unordered_set&lt; typename DGtal::Z3i::Domain::Point &gt; &gt;',['../classDGtal_1_1DigitalSetByAssociativeContainer.html',1,'DGtal']]],
  ['digitalsetbystlset_8583',['DigitalSetBySTLSet',['../classDGtal_1_1DigitalSetBySTLSet.html',1,'DGtal']]],
  ['digitalsetbystlvector_8584',['DigitalSetBySTLVector',['../classDGtal_1_1DigitalSetBySTLVector.html',1,'DGtal']]],
  ['digitalsetconverter_8585',['DigitalSetConverter',['../structDGtal_1_1DigitalSetConverter.html',1,'DGtal']]],
  ['digitalsetdomain_8586',['DigitalSetDomain',['../classDGtal_1_1DigitalSetDomain.html',1,'DGtal']]],
  ['digitalsetdomain_3c_20digitalset_20_3e_8587',['DigitalSetDomain&lt; DigitalSet &gt;',['../classDGtal_1_1DigitalSetDomain.html',1,'DGtal']]],
  ['digitalsetfrommap_8588',['DigitalSetFromMap',['../classDGtal_1_1DigitalSetFromMap.html',1,'DGtal']]],
  ['digitalsetinserter_8589',['DigitalSetInserter',['../classDGtal_1_1DigitalSetInserter.html',1,'DGtal']]],
  ['digitalsetselector_8590',['DigitalSetSelector',['../structDGtal_1_1DigitalSetSelector.html',1,'DGtal']]],
  ['digitalshapescsg_8591',['DigitalShapesCSG',['../classDGtal_1_1DigitalShapesCSG.html',1,'DGtal']]],
  ['digitalshapesintersection_8592',['DigitalShapesIntersection',['../classDGtal_1_1deprecated_1_1DigitalShapesIntersection.html',1,'DGtal::deprecated']]],
  ['digitalshapesminus_8593',['DigitalShapesMinus',['../classDGtal_1_1deprecated_1_1DigitalShapesMinus.html',1,'DGtal::deprecated']]],
  ['digitalshapesunion_8594',['DigitalShapesUnion',['../classDGtal_1_1deprecated_1_1DigitalShapesUnion.html',1,'DGtal::deprecated']]],
  ['digitalsurface_8595',['DigitalSurface',['../classDGtal_1_1DigitalSurface.html',1,'DGtal']]],
  ['digitalsurface2dslice_8596',['DigitalSurface2DSlice',['../classDGtal_1_1DigitalSurface2DSlice.html',1,'DGtal']]],
  ['digitalsurface_5fgraph_5ftraversal_5fcategory_8597',['DigitalSurface_graph_traversal_category',['../structboost_1_1DigitalSurface__graph__traversal__category.html',1,'boost']]],
  ['digitalsurfaceconvolver_8598',['DigitalSurfaceConvolver',['../classDGtal_1_1DigitalSurfaceConvolver.html',1,'DGtal']]],
  ['digitalsurfaceconvolver_3c_20tfunctor_2c_20tkernelfunctor_2c_20tkspace_2c_20tdigitalkernel_2c_202_20_3e_8599',['DigitalSurfaceConvolver&lt; TFunctor, TKernelFunctor, TKSpace, TDigitalKernel, 2 &gt;',['../classDGtal_1_1DigitalSurfaceConvolver_3_01TFunctor_00_01TKernelFunctor_00_01TKSpace_00_01TDigitalKernel_00_012_01_4.html',1,'DGtal']]],
  ['digitalsurfaceconvolver_3c_20tfunctor_2c_20tkernelfunctor_2c_20tkspace_2c_20tdigitalkernel_2c_203_20_3e_8600',['DigitalSurfaceConvolver&lt; TFunctor, TKernelFunctor, TKSpace, TDigitalKernel, 3 &gt;',['../classDGtal_1_1DigitalSurfaceConvolver_3_01TFunctor_00_01TKernelFunctor_00_01TKSpace_00_01TDigitalKernel_00_013_01_4.html',1,'DGtal']]],
  ['digitalsurfaceembedderwithnormalvectorestimator_8601',['DigitalSurfaceEmbedderWithNormalVectorEstimator',['../classDGtal_1_1DigitalSurfaceEmbedderWithNormalVectorEstimator.html',1,'DGtal']]],
  ['digitalsurfaceembedderwithnormalvectorestimatorgradientmap_8602',['DigitalSurfaceEmbedderWithNormalVectorEstimatorGradientMap',['../classDGtal_1_1DigitalSurfaceEmbedderWithNormalVectorEstimatorGradientMap.html',1,'DGtal']]],
  ['digitalsurfacepredicate_8603',['DigitalSurfacePredicate',['../classDGtal_1_1DigitalSurfacePredicate.html',1,'DGtal']]],
  ['digitalsurfacepredicate_3c_20surface_20_3e_8604',['DigitalSurfacePredicate&lt; Surface &gt;',['../classDGtal_1_1DigitalSurfacePredicate.html',1,'DGtal']]],
  ['digitalsurfaceregularization_8605',['DigitalSurfaceRegularization',['../classDGtal_1_1DigitalSurfaceRegularization.html',1,'DGtal']]],
  ['digitaltopology_8606',['DigitalTopology',['../classDGtal_1_1DigitalTopology.html',1,'DGtal']]],
  ['digitaltopologytraits_8607',['DigitalTopologyTraits',['../structDGtal_1_1DigitalTopologyTraits.html',1,'DGtal']]],
  ['digitaltopologytraits_3c_20metricadjacency_3c_20tspace_2c_201_20_3e_2c_20metricadjacency_3c_20tspace_2c_202_20_3e_2c_202_20_3e_8608',['DigitalTopologyTraits&lt; MetricAdjacency&lt; TSpace, 1 &gt;, MetricAdjacency&lt; TSpace, 2 &gt;, 2 &gt;',['../structDGtal_1_1DigitalTopologyTraits_3_01MetricAdjacency_3_01TSpace_00_011_01_4_00_01MetricAdjac06cfee9ede448beddab595341bf8da45.html',1,'DGtal']]],
  ['digitaltopologytraits_3c_20metricadjacency_3c_20tspace_2c_201_20_3e_2c_20metricadjacency_3c_20tspace_2c_202_20_3e_2c_203_20_3e_8609',['DigitalTopologyTraits&lt; MetricAdjacency&lt; TSpace, 1 &gt;, MetricAdjacency&lt; TSpace, 2 &gt;, 3 &gt;',['../structDGtal_1_1DigitalTopologyTraits_3_01MetricAdjacency_3_01TSpace_00_011_01_4_00_01MetricAdjac75a65f102d2af20aaa2508a722cd03c0.html',1,'DGtal']]],
  ['digitaltopologytraits_3c_20metricadjacency_3c_20tspace_2c_201_20_3e_2c_20metricadjacency_3c_20tspace_2c_203_20_3e_2c_203_20_3e_8610',['DigitalTopologyTraits&lt; MetricAdjacency&lt; TSpace, 1 &gt;, MetricAdjacency&lt; TSpace, 3 &gt;, 3 &gt;',['../structDGtal_1_1DigitalTopologyTraits_3_01MetricAdjacency_3_01TSpace_00_011_01_4_00_01MetricAdjacde3734735d1eccc5fbf7d6f7325c8d5f.html',1,'DGtal']]],
  ['digitaltopologytraits_3c_20metricadjacency_3c_20tspace_2c_202_20_3e_2c_20metricadjacency_3c_20tspace_2c_201_20_3e_2c_202_20_3e_8611',['DigitalTopologyTraits&lt; MetricAdjacency&lt; TSpace, 2 &gt;, MetricAdjacency&lt; TSpace, 1 &gt;, 2 &gt;',['../structDGtal_1_1DigitalTopologyTraits_3_01MetricAdjacency_3_01TSpace_00_012_01_4_00_01MetricAdjac201c1779eb2f50e0034539cb53f56f01.html',1,'DGtal']]],
  ['digitaltopologytraits_3c_20metricadjacency_3c_20tspace_2c_202_20_3e_2c_20metricadjacency_3c_20tspace_2c_201_20_3e_2c_203_20_3e_8612',['DigitalTopologyTraits&lt; MetricAdjacency&lt; TSpace, 2 &gt;, MetricAdjacency&lt; TSpace, 1 &gt;, 3 &gt;',['../structDGtal_1_1DigitalTopologyTraits_3_01MetricAdjacency_3_01TSpace_00_012_01_4_00_01MetricAdjac295bf7f227800ad6435fcd18401c4237.html',1,'DGtal']]],
  ['digitaltopologytraits_3c_20metricadjacency_3c_20tspace_2c_203_20_3e_2c_20metricadjacency_3c_20tspace_2c_201_20_3e_2c_203_20_3e_8613',['DigitalTopologyTraits&lt; MetricAdjacency&lt; TSpace, 3 &gt;, MetricAdjacency&lt; TSpace, 1 &gt;, 3 &gt;',['../structDGtal_1_1DigitalTopologyTraits_3_01MetricAdjacency_3_01TSpace_00_013_01_4_00_01MetricAdjac1853805a85cff1808e38908d0ecd7d1b.html',1,'DGtal']]],
  ['dirichletconditions_8614',['DirichletConditions',['../classDGtal_1_1DirichletConditions.html',1,'DGtal']]],
  ['discreteexteriorcalculus_8615',['DiscreteExteriorCalculus',['../classDGtal_1_1DiscreteExteriorCalculus.html',1,'DGtal']]],
  ['discreteexteriorcalculusfactory_8616',['DiscreteExteriorCalculusFactory',['../classDGtal_1_1DiscreteExteriorCalculusFactory.html',1,'DGtal']]],
  ['discreteexteriorcalculussolver_8617',['DiscreteExteriorCalculusSolver',['../classDGtal_1_1DiscreteExteriorCalculusSolver.html',1,'DGtal']]],
  ['display2dfactory_8618',['Display2DFactory',['../structDGtal_1_1Display2DFactory.html',1,'DGtal']]],
  ['display3d_8619',['Display3D',['../classDGtal_1_1concepts_1_1Display3D.html',1,'DGtal::concepts::Display3D&lt; S, KS &gt;'],['../classDGtal_1_1Display3D.html',1,'DGtal::Display3D&lt; Space, KSpace &gt;']]],
  ['display3d_3c_20dgtal_3a_3aspacend_2c_20dgtal_3a_3akhalimskyspacend_20_3e_8620',['Display3D&lt; DGtal::SpaceND, DGtal::KhalimskySpaceND &gt;',['../classDGtal_1_1Display3D.html',1,'DGtal']]],
  ['display3d_3c_20sp_2c_20ksp_20_3e_8621',['Display3D&lt; Sp, KSp &gt;',['../classDGtal_1_1Display3D.html',1,'DGtal']]],
  ['display3d_3c_20space_2c_20kspace_20_3e_8622',['Display3D&lt; Space, KSpace &gt;',['../classDGtal_1_1Display3D.html',1,'DGtal']]],
  ['display3d_3c_20spacend_3c_203_20_3e_2c_20khalimskyspacend_3c_203_20_3e_20_3e_8623',['Display3D&lt; SpaceND&lt; 3 &gt;, KhalimskySpaceND&lt; 3 &gt; &gt;',['../classDGtal_1_1Display3D.html',1,'DGtal']]],
  ['display3d_3c_20z3i_3a_3aspace_2c_20z3i_3a_3akspace_20_3e_8624',['Display3D&lt; Z3i::Space, Z3i::KSpace &gt;',['../classDGtal_1_1Display3D.html',1,'DGtal']]],
  ['display3dfactory_8625',['Display3DFactory',['../structDGtal_1_1Display3DFactory.html',1,'DGtal']]],
  ['display3dfactory_3c_20tspace_2c_20tkspace_20_3e_8626',['Display3DFactory&lt; TSpace, TKSpace &gt;',['../structDGtal_1_1Display3DFactory.html',1,'DGtal']]],
  ['display3dfactory_3c_20z3i_3a_3aspace_2c_20z3i_3a_3akspace_20_3e_8627',['Display3DFactory&lt; Z3i::Space, Z3i::KSpace &gt;',['../structDGtal_1_1Display3DFactory.html',1,'DGtal']]],
  ['distancebreadthfirstvisitor_8628',['DistanceBreadthFirstVisitor',['../classDGtal_1_1DistanceBreadthFirstVisitor.html',1,'DGtal']]],
  ['distancefromdca_8629',['DistanceFromDCA',['../structDGtal_1_1detail_1_1DistanceFromDCA.html',1,'DGtal::detail']]],
  ['distancefromdcaestimator_8630',['DistanceFromDCAEstimator',['../classDGtal_1_1DistanceFromDCAEstimator.html',1,'DGtal']]],
  ['distancefunctor_8631',['DistanceFunctor',['../classDGtal_1_1IteratorCompletionTraits_3_01ArrayImageAdapter_3_01TArrayIterator_00_01TDomain_01_4_01_4_1_1DistanceFunctor.html',1,'DGtal::IteratorCompletionTraits&lt; ArrayImageAdapter&lt; TArrayIterator, TDomain &gt; &gt;']]],
  ['distancefunctorfrompoint_8632',['DistanceFunctorFromPoint',['../classDGtal_1_1DistanceFunctorFromPoint.html',1,'DGtal']]],
  ['distancetransformation_8633',['DistanceTransformation',['../classDGtal_1_1DistanceTransformation.html',1,'DGtal']]],
  ['domainadjacency_8634',['DomainAdjacency',['../classDGtal_1_1DomainAdjacency.html',1,'DGtal']]],
  ['domainadjacency_3c_20objectdomain_2c_20foregroundadjacency_20_3e_8635',['DomainAdjacency&lt; ObjectDomain, ForegroundAdjacency &gt;',['../classDGtal_1_1DomainAdjacency.html',1,'DGtal']]],
  ['domainmetricadjacency_8636',['DomainMetricAdjacency',['../classDGtal_1_1deprecated_1_1DomainMetricAdjacency.html',1,'DGtal::deprecated']]],
  ['domainpredicate_8637',['DomainPredicate',['../structDGtal_1_1functors_1_1DomainPredicate.html',1,'DGtal::functors']]],
  ['domainpredicate_3c_20domain_20_3e_8638',['DomainPredicate&lt; Domain &gt;',['../structDGtal_1_1functors_1_1DomainPredicate.html',1,'DGtal::functors']]],
  ['domainrigidtransformation2d_8639',['DomainRigidTransformation2D',['../classDGtal_1_1functors_1_1DomainRigidTransformation2D.html',1,'DGtal::functors']]],
  ['domainrigidtransformation2d_3c_20domain_2c_20forwardtrans_20_3e_8640',['DomainRigidTransformation2D&lt; Domain, ForwardTrans &gt;',['../classDGtal_1_1functors_1_1DomainRigidTransformation2D.html',1,'DGtal::functors']]],
  ['domainrigidtransformation3d_8641',['DomainRigidTransformation3D',['../classDGtal_1_1functors_1_1DomainRigidTransformation3D.html',1,'DGtal::functors']]],
  ['domainrigidtransformation3d_3c_20domain_2c_20forwardtrans_20_3e_8642',['DomainRigidTransformation3D&lt; Domain, ForwardTrans &gt;',['../classDGtal_1_1functors_1_1DomainRigidTransformation3D.html',1,'DGtal::functors']]],
  ['dot_8643',['Dot',['../structLibBoard_1_1Dot.html',1,'LibBoard']]],
  ['drawablewithboard2d_8644',['DrawableWithBoard2D',['../structDGtal_1_1DrawableWithBoard2D.html',1,'DGtal']]],
  ['drawablewithboard3dto2d_8645',['DrawableWithBoard3DTo2D',['../structDGtal_1_1DrawableWithBoard3DTo2D.html',1,'DGtal']]],
  ['drawablewithdisplay3d_8646',['DrawableWithDisplay3D',['../structDGtal_1_1DrawableWithDisplay3D.html',1,'DGtal']]],
  ['drawwithboard3dto2dmodifier_8647',['DrawWithBoard3DTo2DModifier',['../structDGtal_1_1DrawWithBoard3DTo2DModifier.html',1,'DGtal']]],
  ['drawwithboardmodifier_8648',['DrawWithBoardModifier',['../structDGtal_1_1DrawWithBoardModifier.html',1,'DGtal']]],
  ['drawwithdisplay3dmodifier_8649',['DrawWithDisplay3DModifier',['../structDGtal_1_1DrawWithDisplay3DModifier.html',1,'DGtal']]],
  ['drawwithviewer3dmodifier_8650',['DrawWithViewer3DModifier',['../structDGtal_1_1DrawWithViewer3DModifier.html',1,'DGtal']]],
  ['dslsubsegment_8651',['DSLSubsegment',['../classDGtal_1_1DSLSubsegment.html',1,'DGtal']]],
  ['dssdecorator_8652',['DSSDecorator',['../classDGtal_1_1detail_1_1DSSDecorator.html',1,'DGtal::detail']]],
  ['dssdecorator4concavepart_8653',['DSSDecorator4ConcavePart',['../classDGtal_1_1detail_1_1DSSDecorator4ConcavePart.html',1,'DGtal::detail']]],
  ['dssdecorator4convexpart_8654',['DSSDecorator4ConvexPart',['../classDGtal_1_1detail_1_1DSSDecorator4ConvexPart.html',1,'DGtal::detail']]],
  ['dsslengthestimator_8655',['DSSLengthEstimator',['../classDGtal_1_1DSSLengthEstimator.html',1,'DGtal']]],
  ['dsslengthlessequalfilter_8656',['DSSLengthLessEqualFilter',['../classDGtal_1_1DSSLengthLessEqualFilter.html',1,'DGtal']]],
  ['dssmutefilter_8657',['DSSMuteFilter',['../classDGtal_1_1DSSMuteFilter.html',1,'DGtal']]],
  ['dummyestimatorfromsurfels_8658',['DummyEstimatorFromSurfels',['../structDGtal_1_1functors_1_1DummyEstimatorFromSurfels.html',1,'DGtal::functors']]],
  ['dummyobject_8659',['DummyObject',['../structDGtal_1_1DummyObject.html',1,'DGtal']]],
  ['dynamicbidirectionalsegmentcomputer_8660',['DynamicBidirectionalSegmentComputer',['../structDGtal_1_1DynamicBidirectionalSegmentComputer.html',1,'DGtal']]],
  ['dynamicsegmentcomputer_8661',['DynamicSegmentComputer',['../structDGtal_1_1DynamicSegmentComputer.html',1,'DGtal']]]
];
