DGtal: 2DSliceImageFromVol.cpp File Reference
2DSliceImageFromVol.cpp File Reference
DGtal Examples
Example associated to the tutorial 5 on Image adapter.
#include <iostream>
#include <DGtal/base/Common.h>
#include "DGtal/io/readers/GenericReader.h"
#include "DGtal/io/writers/GenericWriter.h"
#include <DGtal/helpers/StdDefs.h>
#include <DGtal/images/ImageContainerBySTLVector.h>
#include <DGtal/images/ConstImageAdapter.h>
#include "DGtal/kernel/BasicPointFunctors.h"
Functions
int main (int argc, char **argv)
Detailed Description
Example associated to the tutorial 5 on Image adapter.
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Bertrand Kerautret (bertr.nosp@m.and..nosp@m.kerau.nosp@m.tret.nosp@m.@lori.nosp@m.a.fr) LORIA (CNRS, UMR 7503), University of Lorraine, France
Date
2016/05/09
This file is part of the DGtal library.
Definition in file 2DSliceImageFromVol.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 49 of file 2DSliceImageFromVol.cpp.
{
  typedef ImageContainerBySTLVector<Z2i::Domain, unsigned char>  Image2D;
  typedef ImageContainerBySTLVector<Z3i::Domain, unsigned char>  Image3D;
  if(argc < 3)
    {
      trace.error() << "You need to indicate the volumetric image name and slice number as parameters." << std::endl;
      trace.error() << std::endl;
      return 1;
    }
  std::string filename(argv[1]);
  std::string outputFileName = "sliceImage.pgm";
  unsigned int numSlice = atoi(argv[2]);
  trace.beginBlock("Loading file");
  Image3D  image3d = GenericReader< Image3D >::import ( filename );
  functors::Identity id;
  typedef ConstImageAdapter<Image3D, Image2D::Domain, functors::Projector<Z3i::Space>,
                            Image3D::Value,  functors::Identity >  SliceImageAdapter;
  functors::Projector<Z2i::Space >  proj(2);
  Z2i::Domain domain2D(proj(image3d.domain().lowerBound()),
                              proj(image3d.domain().upperBound()));
  DGtal::functors::Projector<Z3i::Space> aSliceFunctor(numSlice);
  aSliceFunctor.initAddOneDim(2);
  SliceImageAdapter sliceImageZ(image3d, domain2D, aSliceFunctor, id);
  trace.endBlock();
  trace.beginBlock("Exporting...");
  sliceImageZ >> outputFileName;
  trace.endBlock();
  return 0;
}
References DGtal::Trace::beginBlock(), DGtal::Trace::endBlock(), DGtal::Trace::error(), DGtal::GenericReader< TContainer, Tdim, TValue >::import(), DGtal::functors::Projector< S >::initAddOneDim(), and DGtal::trace.