DGtal: DGtal::Xe_kComputer< n, Ring, Alloc > Class Template Reference
DGtal::Xe_kComputer< n, Ring, Alloc > Class Template Reference
#include <DGtal/math/MPolynomial.h>
Public Member Functions
Xe_kComputer ()
MPolynomial< n, Ring, Alloc > get (unsigned int k, unsigned int e)
Detailed Description
template<int n, typename Ring, typename Alloc>
class DGtal::Xe_kComputer< n, Ring, Alloc >
Creates a monomial X_k^e
Template Parameters
n the number of indetermionates.
Ring the type for the coefficent ring of the polynomial.
Alloc the type of allocator.
Definition at line 1618 of file MPolynomial.h.
Constructor & Destructor Documentation
Xe_kComputer()
template<int n, typename Ring , typename Alloc > DGtal::Xe_kComputer< n, Ring, Alloc >::Xe_kComputer () inline
Definition at line 1621 of file MPolynomial.h.
{}
Member Function Documentation
get()
template<int n, typename Ring , typename Alloc > MPolynomial< n, Ring, Alloc > DGtal::Xe_kComputer< n, Ring, Alloc >::get (unsigned int k, unsigned int e) inline
Parameters
k the index of the variable (X_k)
e the exponent for X_k
Returns
the 1-variable polynomial X_0^e
Definition at line 1629 of file MPolynomial.h.
    {
      MPolynomial<n, Ring, Alloc> p;
      if ( k == 0 )
        p[e] = Xe_kComputer<n-1,Ring,Alloc>().get( k-1, e );
      else
        p[0] = Xe_kComputer<n-1,Ring,Alloc>().get( k-1, e );
      p.normalize();
      //std::cerr << "Xe_k(" << k << "," << e << ")=" << p << std::endl;
      return p;
    }
References DGtal::Xe_kComputer< n, Ring, Alloc >::get(), and DGtal::MPolynomial< n, TRing, TAlloc >::normalize().
Referenced by DGtal::Xe_kComputer< n, Ring, Alloc >::get(), and DGtal::Xe_k().
The documentation for this class was generated from the following file:
MPolynomial.h