DGtal: ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M > Class Template Reference
ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M > Class Template Reference
Public Member Functions
ArrayXYOfLabelledMap ()
const Value & value (unsigned int l, unsigned int x, unsigned int y) const
void setValue (const Value &val, unsigned int l, unsigned int x, unsigned int y)
unsigned int erase (unsigned int l, unsigned int x, unsigned int y)
void setValueNoNewLabel (const Value &val, unsigned int l, unsigned int x, unsigned int y)
bool hasLabel (unsigned int l, unsigned int x, unsigned int y) const
void getLabels (std::vector< unsigned int > &labels, unsigned int x, unsigned int y) const
unsigned int nbLabels (unsigned int x, unsigned int y) const
void display (ostream &, unsigned int, unsigned int x, unsigned int y)
unsigned long long area () const
Private Types
typedef LabelledMap< Value, L, TWord, N, M > MyLabelledMap
Private Attributes
MyLabelledMap _data [X][Y]
Detailed Description
template<typename Value, unsigned int L, unsigned int X, unsigned int Y, typename TWord, unsigned int N, unsigned int M>
class ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >
Array[X][Y] of LabelledMap<L>
The proposed alternative to the brute-force approach. Generally less than 10 times the memory used by brute force for L >= 16. Approximately 50% slower in most operations, except initialization or used of all labels. In this case outperforms Array[L][X][Y].
Note that 4000*4000*16 is fine on my 8Gb laptop (529Mb). Note that 2000*2000*64 takes 133Mb.
Definition at line 412 of file testLabelledMap-benchmark.cpp.
Member Typedef Documentation
MyLabelledMap
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> typedef LabelledMap< Value, L, TWord, N, M> ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::MyLabelledMap private
Definition at line 413 of file testLabelledMap-benchmark.cpp.
Constructor & Destructor Documentation
ArrayXYOfLabelledMap()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::ArrayXYOfLabelledMap () inline
Definition at line 418 of file testLabelledMap-benchmark.cpp.
{}
Member Function Documentation
area()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> unsigned long long ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::area () const inline
Definition at line 468 of file testLabelledMap-benchmark.cpp.
  {
    unsigned long long total = 0;
    for ( unsigned int y = 0; y < Y; ++y )
      for ( unsigned int x = 0; x < X; ++x )
        {
          unsigned int size = nbLabels( x, y );
          total += sizeof( MyLabelledMap );
          if ( size > (N+1) )
            total += ( 1 + ( size - N - 1 ) / M ) * ( M * sizeof( Value ) + 8 );
        }
    return total;
  }
References ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::nbLabels().
display()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> void ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::display (ostream & , unsigned int , unsigned int x, unsigned int y) inline
Definition at line 462 of file testLabelledMap-benchmark.cpp.
  {
    std::cerr << _data[ x ][ y ] << endl;
  }
References ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::_data.
erase()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> unsigned int ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::erase (unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 433 of file testLabelledMap-benchmark.cpp.
  {
    return _data[ x ][ y ].erase( l );
  }
References ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::_data, and DGtal::LabelledMap< TData, L, TWord, N, M >::erase().
getLabels()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> void ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::getLabels (std::vector< unsigned int > & labels, unsigned int x, unsigned int y) const inline
Definition at line 451 of file testLabelledMap-benchmark.cpp.
  {
    _data[ x ][ y ].labels().getLabels( labels );
  }
References ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::_data, DGtal::Labels< L, TWord >::getLabels(), and DGtal::LabelledMap< TData, L, TWord, N, M >::labels().
hasLabel()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> bool ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::hasLabel (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 445 of file testLabelledMap-benchmark.cpp.
  {
    return _data[ x ][ y ].count( l );
  }
References ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::_data, and DGtal::LabelledMap< TData, L, TWord, N, M >::count().
nbLabels()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> unsigned int ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::nbLabels (unsigned int x, unsigned int y) const inline
Definition at line 458 of file testLabelledMap-benchmark.cpp.
  {
    return _data[ x ][ y ].size();
  }
References ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::_data, and DGtal::LabelledMap< TData, L, TWord, N, M >::size().
Referenced by ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::area().
setValue()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> void ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::setValue (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 427 of file testLabelledMap-benchmark.cpp.
  {
    _data[ x ][ y ][ l ] = val;
  }
References ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::_data.
setValueNoNewLabel()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> void ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::setValueNoNewLabel (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 439 of file testLabelledMap-benchmark.cpp.
  {
    _data[ x ][ y ].fastAt( l ) = val;
  }
References ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::_data, and DGtal::LabelledMap< TData, L, TWord, N, M >::fastAt().
value()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> const Value & ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::value (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 421 of file testLabelledMap-benchmark.cpp.
  {
    return _data[ x ][ y ].fastAt( l );
  }
References ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::_data, and DGtal::LabelledMap< TData, L, TWord, N, M >::fastAt().
Field Documentation
_data
template<typename Value , unsigned int L, unsigned int X, unsigned int Y, typename TWord , unsigned int N, unsigned int M> MyLabelledMap ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::_data[X][Y] private
Definition at line 414 of file testLabelledMap-benchmark.cpp.
Referenced by ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::display(), ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::erase(), ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::getLabels(), ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::hasLabel(), ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::nbLabels(), ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::setValue(), ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::setValueNoNewLabel(), and ArrayXYOfLabelledMap< Value, L, X, Y, TWord, N, M >::value().
The documentation for this class was generated from the following file:
testLabelledMap-benchmark.cpp