DGtal: DynArrayLXY< Value > Class Template Reference
DynArrayLXY< Value > Class Template Reference
Public Types
typedef Value ValueType
Public Member Functions
DynArrayLXY (unsigned int _L, unsigned int _X, unsigned int _Y, Value invalid)
~DynArrayLXY ()
void clear ()
size_t offset (unsigned int l, unsigned int x, unsigned int y) const
const Value & value (unsigned int l, unsigned int x, unsigned int y) const
unsigned int erase (unsigned int l, unsigned int x, unsigned int y)
void setValue (const Value &val, unsigned int l, unsigned int x, unsigned int y)
void setValueNoNewLabel (const Value &val, unsigned int l, unsigned int x, unsigned int y)
bool hasLabel (unsigned int l, unsigned int x, unsigned int y) const
void getLabels (std::vector< unsigned int > &labels, unsigned int x, unsigned int y) const
unsigned int nbLabels (unsigned int x, unsigned int y) const
void display (ostream &, unsigned int, unsigned int, unsigned int)
unsigned long long area () const
Data Fields
const unsigned int L
const unsigned int X
const unsigned int Y
Private Attributes
Value * _data
Value _invalid
Detailed Description
template<typename Value>
class DynArrayLXY< Value >
Array[L][X][Y] of value. Brute-force. High memory consumption. Rather fast except when working with several labels.
Note that 4000*4000*16 is upper limit on my 8Gb laptop (2Gb). Note that 2000*2000*64 is upper limit on my 8Gb laptop (2Gb).
Definition at line 76 of file testMultiMap-benchmark.cpp.
Member Typedef Documentation
ValueType
template<typename Value > typedef Value DynArrayLXY< Value >::ValueType
Definition at line 78 of file testMultiMap-benchmark.cpp.
Constructor & Destructor Documentation
DynArrayLXY()
template<typename Value > DynArrayLXY< Value >::DynArrayLXY (unsigned int _L, unsigned int _X, unsigned int _Y, Value invalid) inline
Definition at line 89 of file testMultiMap-benchmark.cpp.
    : L( _L ), X( _X ), Y( _Y )
  {
    _invalid = invalid;
    _data = new Value[ L * X * Y ];
    clear();
  }
References DynArrayLXY< Value >::_data, DynArrayLXY< Value >::_invalid, DynArrayLXY< Value >::clear(), DynArrayLXY< Value >::L, DynArrayLXY< Value >::X, and DynArrayLXY< Value >::Y.
~DynArrayLXY()
template<typename Value > DynArrayLXY< Value >::~DynArrayLXY () inline
Definition at line 97 of file testMultiMap-benchmark.cpp.
  {
    delete[] _data;
  }
References DynArrayLXY< Value >::_data.
Member Function Documentation
area()
template<typename Value > unsigned long long DynArrayLXY< Value >::area () const inline
Definition at line 169 of file testMultiMap-benchmark.cpp.
  {
    return L * X * Y * sizeof( Value );
  }
References DynArrayLXY< Value >::L, DynArrayLXY< Value >::X, and DynArrayLXY< Value >::Y.
clear()
template<typename Value > void DynArrayLXY< Value >::clear () inline
Definition at line 102 of file testMultiMap-benchmark.cpp.
  {
    for ( unsigned int l = 0; l < L; ++l )
      for ( unsigned int x = 0; x < X; ++x )
        for ( unsigned int y = 0; y < Y; ++y )
          setValue( _invalid, l, x, y );
  }
References DynArrayLXY< Value >::_invalid, DynArrayLXY< Value >::L, DynArrayLXY< Value >::setValue(), DynArrayLXY< Value >::X, and DynArrayLXY< Value >::Y.
Referenced by DynArrayLXY< Value >::DynArrayLXY().
display()
template<typename Value > void DynArrayLXY< Value >::display (ostream & , unsigned int , unsigned int , unsigned int) inline
Definition at line 165 of file testMultiMap-benchmark.cpp.
  {}
erase()
template<typename Value > unsigned int DynArrayLXY< Value >::erase (unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 121 of file testMultiMap-benchmark.cpp.
  {
    size_t offs = offset( l, x, y );
    if ( _data[ offs ] != _invalid )
      {
        _data[ offs ] = _invalid;
        return 1;
      }
    return 0;
  }
References DynArrayLXY< Value >::_data, DynArrayLXY< Value >::_invalid, and DynArrayLXY< Value >::offset().
getLabels()
template<typename Value > void DynArrayLXY< Value >::getLabels (std::vector< unsigned int > & labels, unsigned int x, unsigned int y) const inline
Definition at line 148 of file testMultiMap-benchmark.cpp.
  {
    labels.clear();
    for ( unsigned int l = 0; l < L; ++l )
      if ( hasLabel( l, x, y ) )
        labels.push_back( l );
  }
References DynArrayLXY< Value >::hasLabel(), and DynArrayLXY< Value >::L.
hasLabel()
template<typename Value > bool DynArrayLXY< Value >::hasLabel (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 143 of file testMultiMap-benchmark.cpp.
  {
    return value( l, x, y ) != _invalid;
  }
References DynArrayLXY< Value >::_invalid, and DynArrayLXY< Value >::value().
Referenced by DynArrayLXY< Value >::getLabels(), and DynArrayLXY< Value >::nbLabels().
nbLabels()
template<typename Value > unsigned int DynArrayLXY< Value >::nbLabels (unsigned int x, unsigned int y) const inline
Definition at line 157 of file testMultiMap-benchmark.cpp.
  {
    unsigned int nb = 0;
    for ( unsigned int l = 0; l < L; ++l )
      if ( hasLabel( l, x, y ) ) ++nb;
    return nb;
  }
References DynArrayLXY< Value >::hasLabel(), and DynArrayLXY< Value >::L.
offset()
template<typename Value > size_t DynArrayLXY< Value >::offset (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 111 of file testMultiMap-benchmark.cpp.
  {
    return ( ( l * X ) + x ) * Y + y;
  }
References DynArrayLXY< Value >::X, and DynArrayLXY< Value >::Y.
Referenced by DynArrayLXY< Value >::erase(), DynArrayLXY< Value >::setValue(), DynArrayLXY< Value >::setValueNoNewLabel(), and DynArrayLXY< Value >::value().
setValue()
template<typename Value > void DynArrayLXY< Value >::setValue (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 133 of file testMultiMap-benchmark.cpp.
  {
    _data[ offset( l, x, y ) ] = val;
  }
References DynArrayLXY< Value >::_data, and DynArrayLXY< Value >::offset().
Referenced by DynArrayLXY< Value >::clear().
setValueNoNewLabel()
template<typename Value > void DynArrayLXY< Value >::setValueNoNewLabel (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 138 of file testMultiMap-benchmark.cpp.
  {
    _data[ offset( l, x, y ) ] = val;
  }
References DynArrayLXY< Value >::_data, and DynArrayLXY< Value >::offset().
value()
template<typename Value > const Value & DynArrayLXY< Value >::value (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 116 of file testMultiMap-benchmark.cpp.
  {
    return _data[ offset( l, x, y ) ];
  }
References DynArrayLXY< Value >::_data, and DynArrayLXY< Value >::offset().
Referenced by DynArrayLXY< Value >::hasLabel().
Field Documentation
_data
template<typename Value > Value* DynArrayLXY< Value >::_data private
Definition at line 84 of file testMultiMap-benchmark.cpp.
Referenced by DynArrayLXY< Value >::DynArrayLXY(), DynArrayLXY< Value >::erase(), DynArrayLXY< Value >::setValue(), DynArrayLXY< Value >::setValueNoNewLabel(), DynArrayLXY< Value >::value(), and DynArrayLXY< Value >::~DynArrayLXY().
_invalid
template<typename Value > Value DynArrayLXY< Value >::_invalid private
Definition at line 85 of file testMultiMap-benchmark.cpp.
Referenced by DynArrayLXY< Value >::clear(), DynArrayLXY< Value >::DynArrayLXY(), DynArrayLXY< Value >::erase(), and DynArrayLXY< Value >::hasLabel().
L
template<typename Value > const unsigned int DynArrayLXY< Value >::L
Definition at line 79 of file testMultiMap-benchmark.cpp.
Referenced by DynArrayLXY< Value >::area(), DynArrayLXY< Value >::clear(), DynArrayLXY< Value >::DynArrayLXY(), DynArrayLXY< Value >::getLabels(), and DynArrayLXY< Value >::nbLabels().
X
template<typename Value > const unsigned int DynArrayLXY< Value >::X
Definition at line 80 of file testMultiMap-benchmark.cpp.
Referenced by DynArrayLXY< Value >::area(), DynArrayLXY< Value >::clear(), DynArrayLXY< Value >::DynArrayLXY(), and DynArrayLXY< Value >::offset().
Y
template<typename Value > const unsigned int DynArrayLXY< Value >::Y
Definition at line 81 of file testMultiMap-benchmark.cpp.
Referenced by DynArrayLXY< Value >::area(), DynArrayLXY< Value >::clear(), DynArrayLXY< Value >::DynArrayLXY(), and DynArrayLXY< Value >::offset().
The documentation for this class was generated from the following file:
testMultiMap-benchmark.cpp