DGtal: DynArrayXYOfLabelledMap< Value, L, TWord, N, M > Class Template Reference
DynArrayXYOfLabelledMap< Value, L, TWord, N, M > Class Template Reference
Public Types
typedef Value ValueType
Public Member Functions
DynArrayXYOfLabelledMap (unsigned int _X, unsigned int _Y)
~DynArrayXYOfLabelledMap ()
size_t offset (unsigned int x, unsigned int y) const
void clear ()
const Value & value (unsigned int l, unsigned int x, unsigned int y) const
void setValue (const Value &val, unsigned int l, unsigned int x, unsigned int y)
unsigned int erase (unsigned int l, unsigned int x, unsigned int y)
void setValueNoNewLabel (const Value &val, unsigned int l, unsigned int x, unsigned int y)
bool hasLabel (unsigned int l, unsigned int x, unsigned int y) const
void getLabels (std::vector< unsigned int > &labels, unsigned int x, unsigned int y) const
unsigned int nbLabels (unsigned int x, unsigned int y) const
void display (ostream &, unsigned int, unsigned int x, unsigned int y)
unsigned long long area () const
Data Fields
const unsigned int X
const unsigned int Y
Private Types
typedef LabelledMap< Value, L, TWord, N, M > MyLabelledMap
Private Attributes
MyLabelledMap * _data
Detailed Description
template<typename Value, unsigned int L, typename TWord, unsigned int N, unsigned int M>
class DynArrayXYOfLabelledMap< Value, L, TWord, N, M >
Array[X][Y] of LabelledMap<L>
The proposed alternative to the brute-force approach. Generally less than 10 times the memory used by brute force for L >= 16. Approximately 50% slower in most operations, except initialization or used of all labels. In this case outperforms Array[L][X][Y].
Note that 4000*4000*16 is fine on my 8Gb laptop (529Mb). Note that 2000*2000*64 takes 133Mb.
Definition at line 478 of file testMultiMap-benchmark.cpp.
Member Typedef Documentation
MyLabelledMap
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> typedef LabelledMap< Value, L, TWord, N, M> DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::MyLabelledMap private
Definition at line 479 of file testMultiMap-benchmark.cpp.
ValueType
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> typedef Value DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::ValueType
Definition at line 481 of file testMultiMap-benchmark.cpp.
Constructor & Destructor Documentation
DynArrayXYOfLabelledMap()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::DynArrayXYOfLabelledMap (unsigned int _X, unsigned int _Y) inline
Definition at line 490 of file testMultiMap-benchmark.cpp.
    : X( _X ), Y( _Y )
  {
    _data = new MyLabelledMap[ X * Y ];
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::X, and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::Y.
~DynArrayXYOfLabelledMap()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::~DynArrayXYOfLabelledMap () inline
Definition at line 496 of file testMultiMap-benchmark.cpp.
  {
    delete[] _data;
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data.
Member Function Documentation
area()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> unsigned long long DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::area () const inline
Definition at line 562 of file testMultiMap-benchmark.cpp.
  {
    unsigned long long total = 0;
    for ( unsigned int y = 0; y < Y; ++y )
      for ( unsigned int x = 0; x < X; ++x )
        {
          unsigned int size = nbLabels( x, y );
          total += sizeof( MyLabelledMap );
          if ( size > (N+1) )
            total += ( 1 + ( size - N - 1 ) / M ) * ( M * sizeof( Value ) + 8 );
        }
    return total;
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::nbLabels(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::X, and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::Y.
clear()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> void DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::clear () inline
Definition at line 507 of file testMultiMap-benchmark.cpp.
  {
      for ( unsigned int y = 0; y < Y; ++y )
        for ( unsigned int x = 0; x < X; ++x )
          _data[ offset( x, y ) ].clear();
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, DGtal::LabelledMap< TData, L, TWord, N, M >::clear(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::X, and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::Y.
display()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> void DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::display (ostream & , unsigned int , unsigned int x, unsigned int y) inline
Definition at line 556 of file testMultiMap-benchmark.cpp.
  {
    std::cerr << _data[ offset( x, y ) ] << endl;
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset().
erase()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> unsigned int DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::erase (unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 527 of file testMultiMap-benchmark.cpp.
  {
    return _data[ offset( x, y ) ].erase( l );
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, DGtal::LabelledMap< TData, L, TWord, N, M >::erase(), and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset().
getLabels()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> void DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::getLabels (std::vector< unsigned int > & labels, unsigned int x, unsigned int y) const inline
Definition at line 545 of file testMultiMap-benchmark.cpp.
  {
    _data[ offset( x, y ) ].labels().getLabels( labels );
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, DGtal::Labels< L, TWord >::getLabels(), DGtal::LabelledMap< TData, L, TWord, N, M >::labels(), and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset().
hasLabel()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> bool DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::hasLabel (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 539 of file testMultiMap-benchmark.cpp.
  {
    return _data[ offset( x, y ) ].count( l );
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, DGtal::LabelledMap< TData, L, TWord, N, M >::count(), and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset().
nbLabels()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> unsigned int DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::nbLabels (unsigned int x, unsigned int y) const inline
Definition at line 552 of file testMultiMap-benchmark.cpp.
  {
    return static_cast<unsigned int>(_data[ offset( x, y ) ].size());
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset(), and DGtal::LabelledMap< TData, L, TWord, N, M >::size().
Referenced by DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::area().
offset()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> size_t DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset (unsigned int x, unsigned int y) const inline
Definition at line 501 of file testMultiMap-benchmark.cpp.
  {
    return x * Y + y;
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::Y.
Referenced by DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::clear(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::display(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::erase(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::getLabels(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::hasLabel(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::nbLabels(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::setValue(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::setValueNoNewLabel(), and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::value().
setValue()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> void DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::setValue (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 521 of file testMultiMap-benchmark.cpp.
  {
    _data[ offset( x, y ) ][ l ] = val;
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset().
setValueNoNewLabel()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> void DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::setValueNoNewLabel (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 533 of file testMultiMap-benchmark.cpp.
  {
    _data[ offset( x, y ) ].fastAt( l ) = val;
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, DGtal::LabelledMap< TData, L, TWord, N, M >::fastAt(), and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset().
value()
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> const Value & DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::value (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 515 of file testMultiMap-benchmark.cpp.
  {
    return _data[ offset( x, y ) ].fastAt( l );
  }
References DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data, DGtal::LabelledMap< TData, L, TWord, N, M >::fastAt(), and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset().
Field Documentation
_data
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> MyLabelledMap* DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::_data private
Definition at line 486 of file testMultiMap-benchmark.cpp.
Referenced by DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::clear(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::display(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::DynArrayXYOfLabelledMap(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::erase(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::getLabels(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::hasLabel(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::nbLabels(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::setValue(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::setValueNoNewLabel(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::value(), and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::~DynArrayXYOfLabelledMap().
X
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> const unsigned int DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::X
Definition at line 482 of file testMultiMap-benchmark.cpp.
Referenced by DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::area(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::clear(), and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::DynArrayXYOfLabelledMap().
Y
template<typename Value , unsigned int L, typename TWord , unsigned int N, unsigned int M> const unsigned int DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::Y
Definition at line 483 of file testMultiMap-benchmark.cpp.
Referenced by DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::area(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::clear(), DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::DynArrayXYOfLabelledMap(), and DynArrayXYOfLabelledMap< Value, L, TWord, N, M >::offset().
The documentation for this class was generated from the following file:
testMultiMap-benchmark.cpp