DGtal: ArrayXYOfMap< Value, L, X, Y > Class Template Reference
ArrayXYOfMap< Value, L, X, Y > Class Template Reference
Public Member Functions
ArrayXYOfMap ()
void clear ()
const Value & value (unsigned int l, unsigned int x, unsigned int y)
unsigned int erase (unsigned int l, unsigned int x, unsigned int y)
void setValue (const Value &val, unsigned int l, unsigned int x, unsigned int y)
void setValueNoNewLabel (const Value &val, unsigned int l, unsigned int x, unsigned int y)
bool hasLabel (unsigned int l, unsigned int x, unsigned int y) const
void getLabels (std::vector< unsigned int > &labels, unsigned int x, unsigned int y) const
unsigned int nbLabels (unsigned int x, unsigned int y) const
void display (ostream &, unsigned int, unsigned int, unsigned int)
unsigned long long area () const
Private Types
typedef std::map< unsigned int, Value > MyMap
typedef MyMap::const_iterator ConstIterator
Private Attributes
MyMap _data [X][Y]
Detailed Description
template<typename Value, unsigned int L, unsigned int X, unsigned int Y>
class ArrayXYOfMap< Value, L, X, Y >
Array[X][Y] of map<L,Value> Intermediate approach. Slower (between 30% and 40%) than ArrayXYOfLabelledMap and takes 50% to 100% twice as much place.
Note that 4000*4000*16 takes 861Mb. Note that 2000*2000*64 takes 218Mb.
Definition at line 161 of file testLabelledMap-benchmark.cpp.
Member Typedef Documentation
ConstIterator
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> typedef MyMap::const_iterator ArrayXYOfMap< Value, L, X, Y >::ConstIterator private
Definition at line 163 of file testLabelledMap-benchmark.cpp.
MyMap
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> typedef std::map<unsigned int, Value> ArrayXYOfMap< Value, L, X, Y >::MyMap private
Definition at line 162 of file testLabelledMap-benchmark.cpp.
Constructor & Destructor Documentation
ArrayXYOfMap()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> ArrayXYOfMap< Value, L, X, Y >::ArrayXYOfMap () inline
Definition at line 168 of file testLabelledMap-benchmark.cpp.
  {
  }
Member Function Documentation
area()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> unsigned long long ArrayXYOfMap< Value, L, X, Y >::area () const inline
Definition at line 226 of file testLabelledMap-benchmark.cpp.
  {
    unsigned long long total = 0;
    for ( unsigned int y = 0; y < Y; ++y )
      for ( unsigned int x = 0; x < X; ++x )
        {
          unsigned int size = nbLabels( x, y );
          total += ( size + 1 ) *
            ( sizeof( Value ) // one value per node
              + 3 * sizeof( Value* ) // three pointers
              + 2 //_RbTreeColor { _S_red = false, _S_black = true };
              + 8 // dynamic allocation );
              );
        }
    return total;
  }
References ArrayXYOfMap< Value, L, X, Y >::nbLabels().
clear()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfMap< Value, L, X, Y >::clear () inline
Definition at line 173 of file testLabelledMap-benchmark.cpp.
  {
      for ( unsigned int y = 0; y < Y; ++y )
        for ( unsigned int x = 0; x < X; ++x )
          _data[ x ][ y ].clear();
  }
References ArrayXYOfMap< Value, L, X, Y >::_data, and ArrayXYOfMap< Value, L, X, Y >::clear().
Referenced by ArrayXYOfMap< Value, L, X, Y >::clear().
display()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfMap< Value, L, X, Y >::display (ostream & , unsigned int , unsigned int , unsigned int) inline
Definition at line 221 of file testLabelledMap-benchmark.cpp.
  {}
erase()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> unsigned int ArrayXYOfMap< Value, L, X, Y >::erase (unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 186 of file testLabelledMap-benchmark.cpp.
  {
    return _data[ x ][ y ].erase( l );
  }
References ArrayXYOfMap< Value, L, X, Y >::_data.
getLabels()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfMap< Value, L, X, Y >::getLabels (std::vector< unsigned int > & labels, unsigned int x, unsigned int y) const inline
Definition at line 207 of file testLabelledMap-benchmark.cpp.
  {
    labels.clear();
    for ( ConstIterator it = _data[ x ][ y ].begin(), it_end = _data[ x ][ y ].end();
          it != it_end; ++it )
      labels.push_back( (*it).first );
  }
References ArrayXYOfMap< Value, L, X, Y >::_data.
hasLabel()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> bool ArrayXYOfMap< Value, L, X, Y >::hasLabel (unsigned int l, unsigned int x, unsigned int y) const inline
Definition at line 202 of file testLabelledMap-benchmark.cpp.
  {
    return _data[ x ][ y ].count( l ) != 0;
  }
References ArrayXYOfMap< Value, L, X, Y >::_data.
nbLabels()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> unsigned int ArrayXYOfMap< Value, L, X, Y >::nbLabels (unsigned int x, unsigned int y) const inline
Definition at line 216 of file testLabelledMap-benchmark.cpp.
  {
    return (unsigned int)_data[ x ][ y ].size();
  }
References ArrayXYOfMap< Value, L, X, Y >::_data.
Referenced by ArrayXYOfMap< Value, L, X, Y >::area().
setValue()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfMap< Value, L, X, Y >::setValue (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 192 of file testLabelledMap-benchmark.cpp.
  {
    _data[ x ][ y ][ l ] = val;
  }
References ArrayXYOfMap< Value, L, X, Y >::_data.
setValueNoNewLabel()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> void ArrayXYOfMap< Value, L, X, Y >::setValueNoNewLabel (const Value & val, unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 197 of file testLabelledMap-benchmark.cpp.
  {
    _data[ x ][ y ][ l ] = val;
  }
References ArrayXYOfMap< Value, L, X, Y >::_data.
value()
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> const Value & ArrayXYOfMap< Value, L, X, Y >::value (unsigned int l, unsigned int x, unsigned int y) inline
Definition at line 181 of file testLabelledMap-benchmark.cpp.
  {
    return _data[ x ][ y ][ l ];
  }
References ArrayXYOfMap< Value, L, X, Y >::_data.
Field Documentation
_data
template<typename Value , unsigned int L, unsigned int X, unsigned int Y> MyMap ArrayXYOfMap< Value, L, X, Y >::_data[X][Y] private
Definition at line 164 of file testLabelledMap-benchmark.cpp.
Referenced by ArrayXYOfMap< Value, L, X, Y >::clear(), ArrayXYOfMap< Value, L, X, Y >::erase(), ArrayXYOfMap< Value, L, X, Y >::getLabels(), ArrayXYOfMap< Value, L, X, Y >::hasLabel(), ArrayXYOfMap< Value, L, X, Y >::nbLabels(), ArrayXYOfMap< Value, L, X, Y >::setValue(), ArrayXYOfMap< Value, L, X, Y >::setValueNoNewLabel(), and ArrayXYOfMap< Value, L, X, Y >::value().
The documentation for this class was generated from the following file:
testLabelledMap-benchmark.cpp