DGtal: testDigitalSetToCellularGridConverter Class Reference
testDigitalSetToCellularGridConverter Class Reference
Public Member Functions
testDigitalSetToCellularGridConverter ()
bool extractCells ()
Private Types
typedef Flower2D< Space > MyEuclideanShape
typedef map< Cell, CubicalCellData > Map
typedef CubicalComplex< KSpace, Map > CC
typedef GaussDigitizer< Space, MyEuclideanShape > MyGaussDigitizer
Private Attributes
KSpace K
MyGaussDigitizer digShape
Detailed Description
Definition at line 53 of file testDigitalSetToCellularGridConverter.cpp.
Member Typedef Documentation
CC
typedef CubicalComplex< KSpace, Map > testDigitalSetToCellularGridConverter::CC private
Definition at line 57 of file testDigitalSetToCellularGridConverter.cpp.
Map
typedef map<Cell, CubicalCellData> testDigitalSetToCellularGridConverter::Map private
Definition at line 56 of file testDigitalSetToCellularGridConverter.cpp.
MyEuclideanShape
typedef Flower2D< Space > testDigitalSetToCellularGridConverter::MyEuclideanShape private
Definition at line 55 of file testDigitalSetToCellularGridConverter.cpp.
MyGaussDigitizer
typedef GaussDigitizer< Space, MyEuclideanShape > testDigitalSetToCellularGridConverter::MyGaussDigitizer private
Definition at line 58 of file testDigitalSetToCellularGridConverter.cpp.
Constructor & Destructor Documentation
testDigitalSetToCellularGridConverter()
testDigitalSetToCellularGridConverter::testDigitalSetToCellularGridConverter () inline
Definition at line 63 of file testDigitalSetToCellularGridConverter.cpp.
{}
Member Function Documentation
extractCells()
bool testDigitalSetToCellularGridConverter::extractCells () inline
Definition at line 64 of file testDigitalSetToCellularGridConverter.cpp.
  {
    MyEuclideanShape shape( RealPoint( 0.0, 0.0 ), 16, 5, 5, M_PI_2/2. );
    digShape.attach( shape );
    digShape.init ( shape.getLowerBound(), shape.getUpperBound(), 1.0 );
    Domain domainShape = digShape.getDomain();
    K.init (  domainShape.lowerBound(), domainShape.upperBound(), true );
    DigitalSet aSet ( domainShape );
    Shapes<Domain>::digitalShaper ( aSet, digShape );
    CC complex ( K );
    complex.construct < DigitalSet > ( aSet );
    return true;
  }
References DGtal::GaussDigitizer< TSpace, TEuclideanShape >::attach(), DGtal::Shapes< TDomain >::digitalShaper(), digShape, DGtal::GaussDigitizer< TSpace, TEuclideanShape >::getDomain(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), DGtal::GaussDigitizer< TSpace, TEuclideanShape >::init(), K, DGtal::HyperRectDomain< TSpace >::lowerBound(), and DGtal::HyperRectDomain< TSpace >::upperBound().
Field Documentation
digShape
MyGaussDigitizer testDigitalSetToCellularGridConverter::digShape private
Definition at line 61 of file testDigitalSetToCellularGridConverter.cpp.
Referenced by extractCells().
K
KSpace testDigitalSetToCellularGridConverter::K private
Definition at line 60 of file testDigitalSetToCellularGridConverter.cpp.
Referenced by extractCells().
The documentation for this class was generated from the following file:
testDigitalSetToCellularGridConverter.cpp