DGtal: testLambdaMST2D Class Reference
testLambdaMST2D Class Reference
Public Member Functions
testLambdaMST2D ()
bool lambda64ByPoint ()
bool lambda64 ()
Private Types
typedef vector< Point > Range
typedef Range::const_iterator ConstIterator
typedef ArithmeticalDSSComputer< ConstIterator, int, 8 > SegmentComputer
typedef SaturatedSegmentation< SegmentComputer > Segmentation
Private Attributes
Range curve
Detailed Description
Definition at line 53 of file testLambdaMST2D.cpp.
Member Typedef Documentation
ConstIterator
typedef Range::const_iterator testLambdaMST2D::ConstIterator private
Definition at line 56 of file testLambdaMST2D.cpp.
Range
typedef vector< Point > testLambdaMST2D::Range private
Definition at line 55 of file testLambdaMST2D.cpp.
Segmentation
typedef SaturatedSegmentation<SegmentComputer> testLambdaMST2D::Segmentation private
Definition at line 58 of file testLambdaMST2D.cpp.
SegmentComputer
typedef ArithmeticalDSSComputer< ConstIterator, int, 8 > testLambdaMST2D::SegmentComputer private
Definition at line 57 of file testLambdaMST2D.cpp.
Constructor & Destructor Documentation
testLambdaMST2D()
testLambdaMST2D::testLambdaMST2D () inline
Definition at line 62 of file testLambdaMST2D.cpp.
  {
    fstream inputStream;
    inputStream.open ( (testPath + "samples/sinus2D4.dat").c_str(), ios::in );
    try {
      curve = PointListReader<Point>::getPointsFromInputStream ( inputStream );
      if ( curve.size() == 0) throw IOException();
    } catch (DGtal::IOException & ioe) {
      trace.error() << "Size is null." << endl;
    }
  }
References curve, DGtal::Trace::error(), DGtal::PointListReader< TPoint >::getPointsFromInputStream(), and DGtal::trace.
Member Function Documentation
lambda64()
bool testLambdaMST2D::lambda64 () inline
Definition at line 82 of file testLambdaMST2D.cpp.
  {
    Segmentation segmenter ( curve.begin(), curve.end(), SegmentComputer() );
    LambdaMST2D < Segmentation > lmst64;
    lmst64.attach ( segmenter );
    lmst64.init ( curve.begin(), curve.end() );
    std::vector < RealVector > tangent;
    lmst64.eval < back_insert_iterator< vector < RealVector > > > ( curve.begin(), curve.end(),  back_inserter ( tangent ) );
    return true;
  }
References DGtal::LambdaMST2DEstimator< TSpace, TSegmentation, Functor >::attach(), curve, DGtal::LambdaMST2DEstimator< TSpace, TSegmentation, Functor >::eval(), and DGtal::LambdaMST2DEstimator< TSpace, TSegmentation, Functor >::init().
Referenced by main().
lambda64ByPoint()
bool testLambdaMST2D::lambda64ByPoint () inline
Definition at line 73 of file testLambdaMST2D.cpp.
  {
    Segmentation segmenter ( curve.begin(), curve.end(), SegmentComputer() );
    LambdaMST2D < Segmentation > lmst64;
    lmst64.attach ( segmenter );
    for ( ConstIterator it = curve.begin(); it != curve.end(); ++it )
      lmst64.eval ( *it );
    return true;
  }
References DGtal::LambdaMST2DEstimator< TSpace, TSegmentation, Functor >::attach(), curve, and DGtal::LambdaMST2DEstimator< TSpace, TSegmentation, Functor >::eval().
Referenced by main().
Field Documentation
curve
Range testLambdaMST2D::curve private
Definition at line 60 of file testLambdaMST2D.cpp.
Referenced by lambda64(), lambda64ByPoint(), and testLambdaMST2D().
The documentation for this class was generated from the following file:
testLambdaMST2D.cpp