DGtal: DGtal::Quantity< T > Struct Template Reference
DGtal::Quantity< T > Struct Template Reference
Wrapper for array of quantities.
#include <DGtal/io/Display3D.h>
Public Types
using QType = std::map< std::string, std::vector< T > >
Public Member Functions
QType & operator[] (int idx)
const QType & operator[] (int idx) const
QType & operator[] (const QuantityScale &scale)
const QType & operator[] (const QuantityScale &scale) const
Data Fields
std::array< QType, static_cast< size_t >(QuantityScale::UNKNOWN)> data
Detailed Description
template<typename T>
struct DGtal::Quantity< T >
Wrapper for array of quantities.
Post C++23, enums are not convertible to int anymore. To avoid casts everytime, we wrap the operators inside this class.
Definition at line 223 of file Display3D.h.
Member Typedef Documentation
QType
template<typename T > using DGtal::Quantity< T >::QType = std::map<std::string, std::vector<T> >
Definition at line 224 of file Display3D.h.
Member Function Documentation
operator[]() [1/4]
template<typename T > QType & DGtal::Quantity< T >::operator[] (const QuantityScale & scale) inline
Definition at line 230 of file Display3D.h.
{
        return data[static_cast<size_t>(scale)];
      };
References DGtal::Quantity< T >::data, and scale.
operator[]() [2/4]
template<typename T > const QType & DGtal::Quantity< T >::operator[] (const QuantityScale & scale) const inline
Definition at line 234 of file Display3D.h.
{
        return data[static_cast<size_t>(scale)];
      };
References DGtal::Quantity< T >::data, and scale.
operator[]() [3/4]
template<typename T > QType & DGtal::Quantity< T >::operator[] (int idx) inline
Definition at line 226 of file Display3D.h.
{ return data[idx]; }
References DGtal::Quantity< T >::data.
operator[]() [4/4]
template<typename T > const QType & DGtal::Quantity< T >::operator[] (int idx) const inline
Definition at line 228 of file Display3D.h.
{ return data[idx]; }
References DGtal::Quantity< T >::data.
Field Documentation
data
template<typename T > std::array<QType, static_cast<size_t>(QuantityScale::UNKNOWN)> DGtal::Quantity< T >::data
Definition at line 238 of file Display3D.h.
Referenced by DGtal::Quantity< T >::operator[](), DGtal::Quantity< T >::operator[](), DGtal::Quantity< T >::operator[](), and DGtal::Quantity< T >::operator[]().
The documentation for this struct was generated from the following file:
Display3D.h