DGtal: MultiScaleAnalyzer< KSpace, N > Struct Template Reference
MultiScaleAnalyzer< KSpace, N > Struct Template Reference
Public Types
typedef KSpace::Point Point
typedef NeighborhoodConvexityAnalyzer< KSpace, N > NCA
typedef std::pair< int, int > Geometry
Static Public Member Functions
template<typename ImagePtr >
static std::vector< Geometry > multiscale_run (const KSpace &aK, const std::vector< Point > &pts, ImagePtr bimage)
Detailed Description
template<typename KSpace, int N>
struct MultiScaleAnalyzer< KSpace, N >
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp.
Definition at line 195 of file fullConvexityAnalysis3D.cpp.
Member Typedef Documentation
Geometry
template<typename KSpace , int N> typedef std::pair< int, int > MultiScaleAnalyzer< KSpace, N >::Geometry
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp.
Definition at line 198 of file fullConvexityAnalysis3D.cpp.
NCA
template<typename KSpace , int N> typedef NeighborhoodConvexityAnalyzer< KSpace, N > MultiScaleAnalyzer< KSpace, N >::NCA
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp.
Definition at line 197 of file fullConvexityAnalysis3D.cpp.
Point
template<typename KSpace , int N> typedef KSpace::Point MultiScaleAnalyzer< KSpace, N >::Point
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp.
Definition at line 196 of file fullConvexityAnalysis3D.cpp.
Member Function Documentation
multiscale_run()
template<typename KSpace , int N> template<typename ImagePtr > static std::vector< Geometry > MultiScaleAnalyzer< KSpace, N >::multiscale_run (const KSpace & aK, const std::vector< Point > & pts, ImagePtr bimage) inline static
Examples
geometry/volumes/fullConvexityAnalysis3D.cpp.
Definition at line 203 of file fullConvexityAnalysis3D.cpp.
  {
    auto prev_geometry
      = MultiScaleAnalyzer< KSpace, N-1>::multiscale_run( aK, pts, bimage );
    trace.info() << "------- Analyzing scale " << N << " --------" << std::endl;
    std::vector< int > geom( prev_geometry.size() );
    for ( size_t i = 0; i < geom.size(); i++ )
      geom[ i ] = ( prev_geometry[ i ].first == N-1 ? 0x1 : 0x0 )
        |  ( prev_geometry[ i ].second == N-1 ? 0x2 : 0x0 );
    Analyzer< KSpace, N>::run( geom, aK, pts, bimage );
    for ( size_t i = 0; i < geom.size(); i++ ) {
      prev_geometry[ i ].first  += ( geom[ i ] & 0x1 ) ? 1 : 0;
      prev_geometry[ i ].second += ( geom[ i ] & 0x2 ) ? 1 : 0;
    }
    return prev_geometry;
  }
References DGtal::Trace::info(), MultiScaleAnalyzer< KSpace, N >::multiscale_run(), Analyzer< KSpace, N >::run(), and DGtal::trace.
Referenced by main(), and MultiScaleAnalyzer< KSpace, N >::multiscale_run().
The documentation for this struct was generated from the following file:
fullConvexityAnalysis3D.cpp