DGtal: Fixture_isthmus Struct Reference
Fixture_isthmus Struct Reference
Public Types
using Point = DGtal::Z3i::Point
using Domain = DGtal::Z3i::Domain
using KSpace = DGtal::Z3i::KSpace
using FixtureDigitalTopology = DGtal::Z3i::DT26_6
using FixtureDigitalSet = DGtal::DigitalSetByAssociativeContainer< DGtal::Z3i::Domain, std::unordered_set< typename DGtal::Z3i::Domain::Point > >
using FixtureMap = std::unordered_map< KSpace::Cell, CubicalCellData >
using FixtureComplex = DGtal::VoxelComplex< KSpace, FixtureMap >
Public Member Functions
Fixture_isthmus ()
FixtureDigitalSet create_set ()
FixtureComplex & create_complex_from_set (const FixtureDigitalSet &input_set)
Data Fields
KSpace ks_fixture
FixtureComplex complex_fixture
FixtureDigitalSet set_fixture
Detailed Description
Definition at line 613 of file testVoxelComplex.cpp.
Member Typedef Documentation
Domain
using Fixture_isthmus::Domain = DGtal::Z3i::Domain
Definition at line 618 of file testVoxelComplex.cpp.
FixtureComplex
using Fixture_isthmus::FixtureComplex = DGtal::VoxelComplex<KSpace, FixtureMap>
Definition at line 626 of file testVoxelComplex.cpp.
FixtureDigitalSet
using Fixture_isthmus::FixtureDigitalSet = DGtal::DigitalSetByAssociativeContainer< DGtal::Z3i::Domain, std::unordered_set<typename DGtal::Z3i::Domain::Point> >
Definition at line 622 of file testVoxelComplex.cpp.
FixtureDigitalTopology
using Fixture_isthmus::FixtureDigitalTopology = DGtal::Z3i::DT26_6
Definition at line 621 of file testVoxelComplex.cpp.
FixtureMap
using Fixture_isthmus::FixtureMap = std::unordered_map<KSpace::Cell, CubicalCellData>
Definition at line 625 of file testVoxelComplex.cpp.
KSpace
using Fixture_isthmus::KSpace = DGtal::Z3i::KSpace
Definition at line 619 of file testVoxelComplex.cpp.
Point
using Fixture_isthmus::Point = DGtal::Z3i::Point
Definition at line 617 of file testVoxelComplex.cpp.
Constructor & Destructor Documentation
Fixture_isthmus()
Fixture_isthmus::Fixture_isthmus () inline
Definition at line 638 of file testVoxelComplex.cpp.
                      : complex_fixture(ks_fixture), set_fixture(create_set()) {
        create_complex_from_set(set_fixture);
    }
References create_complex_from_set(), and set_fixture.
Member Function Documentation
create_complex_from_set()
FixtureComplex & Fixture_isthmus::create_complex_from_set (const FixtureDigitalSet & input_set) inline
Definition at line 706 of file testVoxelComplex.cpp.
{
        ks_fixture.init(input_set.domain().lowerBound(),
                        input_set.domain().upperBound(), true);
        complex_fixture = FixtureComplex(ks_fixture);
        complex_fixture.construct(input_set);
        return complex_fixture;
    }
References complex_fixture, DGtal::VoxelComplex< TKSpace, TCellContainer >::construct(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), ks_fixture, DGtal::HyperRectDomain< TSpace >::lowerBound(), and DGtal::HyperRectDomain< TSpace >::upperBound().
Referenced by Fixture_isthmus().
create_set()
FixtureDigitalSet Fixture_isthmus::create_set () inline
Definition at line 645 of file testVoxelComplex.cpp.
{
        using namespace DGtal;
        Point p1(-10, -10, -10);
        Point p2(10, 10, 10);
        Domain domain(p1, p2);
        FixtureDigitalSet fig6_set(domain);
        Point c00(0, 0, 0);
        fig6_set.insertNew(c00);
        Point c01(-1, 0, 0);
        fig6_set.insertNew(c01);
        Point c02(-2, 0, 0);
        fig6_set.insertNew(c02);
        Point c03(-2, 0, 1);
        fig6_set.insertNew(c03);
        Point c10(0, 1, 0);
        fig6_set.insertNew(c10);
        Point y(-1, 1, 0);
        fig6_set.insertNew(y);
        Point c12(-2, 1, 0);
        fig6_set.insertNew(c12);
        Point c13(-2, 1, 1);
        fig6_set.insertNew(c13);
        Point c20(0, 2, 0);
        fig6_set.insertNew(c20);
        Point c21(-1, 2, 0);
        fig6_set.insertNew(c21);
        Point c22(-1, 2, 1);
        fig6_set.insertNew(c22);
        Point c33(-1, 2, -1);
        fig6_set.insertNew(c33);
        Point c30(-1, 3, 0);
        fig6_set.insertNew(c30);
        Point c31(-1, 3, 1);
        fig6_set.insertNew(c31);
        Point x(-1, 4, 0);
        fig6_set.insertNew(x);
        Point c50(-1, 5, 0);
        fig6_set.insertNew(c50);
        Point c51(-1, 5, -1);
        fig6_set.insertNew(c51);
        Point c52(-2, 5, 0);
        fig6_set.insertNew(c52);
        Point c60(-1, 6, 0);
        fig6_set.insertNew(c60);
        Point c61(-2, 6, 0);
        fig6_set.insertNew(c61);
        Point c62(-2, 6, -1);
        fig6_set.insertNew(c62);
        return fig6_set;
    }
References domain, and DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::insertNew().
Field Documentation
complex_fixture
FixtureComplex Fixture_isthmus::complex_fixture
Definition at line 631 of file testVoxelComplex.cpp.
Referenced by create_complex_from_set().
ks_fixture
KSpace Fixture_isthmus::ks_fixture
Definition at line 630 of file testVoxelComplex.cpp.
Referenced by create_complex_from_set().
set_fixture
FixtureDigitalSet Fixture_isthmus::set_fixture
Definition at line 632 of file testVoxelComplex.cpp.
Referenced by Fixture_isthmus().
The documentation for this struct was generated from the following file:
testVoxelComplex.cpp