DGtal: A< TC, TD > Class Template Reference
A< TC, TD > Class Template Reference
Public Types
typedef TC C
Public Member Functions
A (int _a)
A (const A &other)
A & operator= (const A &other)
~A ()
A (int _a)
A (const A &other)
A & operator= (const A &other)
~A ()
A (int _a)
A (const A &other)
A & operator= (const A &other)
~A ()
A (const C &c)
Data Fields
int a
Static Public Attributes
static int nb = 0
Detailed Description
template<typename TC, typename TD>
class A< TC, TD >
Examples
examples/io/external-viewers/polyscope/exampleGenericLatticeConvexHull3D.cpp, examples/io/external-viewers/polyscope/exampleGenericLatticeConvexHull4D.cpp, examples/tutorial-examples/polyhedralizer.cpp, geometry/curves/exampleDSLSubsegment.cpp, geometry/tools/exampleAffineGeometry.cpp, geometry/volumes/standardDigitalPolyhedronBuilder3D.cpp, and tutorial-examples/polyhedralizer.cpp.
Definition at line 43 of file testCountedConstPtrOrConstPtr.cpp.
Member Typedef Documentation
C
template<typename TC , typename TD > typedef TC A< TC, TD >::C
Definition at line 46 of file testPartialTemplateSpecialization.cpp.
Constructor & Destructor Documentation
A() [1/7]
template<typename TC , typename TD > A< TC, TD >::A (int _a) inline
Definition at line 44 of file testCountedConstPtrOrConstPtr.cpp.
              : a( _a )
  {
    ++nb;
    trace.info() << "#" << nb << " A::A( int ), a is " << a << std::endl;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
A() [2/7]
template<typename TC , typename TD > A< TC, TD >::A (const A< TC, TD > & other) inline
Definition at line 49 of file testCountedConstPtrOrConstPtr.cpp.
                      : a( other.a )
  {
    ++nb;
    trace.info() << "#" << nb << " A::A( const A& ), a is " << a << std::endl;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
~A() [1/3]
template<typename TC , typename TD > A< TC, TD >::~A () inline
Definition at line 61 of file testCountedConstPtrOrConstPtr.cpp.
  {
    --nb;
    trace.info() << "#" << nb << " A::~A(), a was " << a << std::endl;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
A() [3/7]
template<typename TC , typename TD > A< TC, TD >::A (int _a) inline
Definition at line 107 of file testCountedPtr.cpp.
              : a( _a )
  {
    ++nb;
    trace.info() << "#" << nb << " A::A( int ), a is " << a << std::endl;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
A() [4/7]
template<typename TC , typename TD > A< TC, TD >::A (const A< TC, TD > & other) inline
Definition at line 112 of file testCountedPtr.cpp.
                      : a( other.a )
  {
    ++nb;
    trace.info() << "#" << nb << " A::A( const A& ), a is " << a << std::endl;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
~A() [2/3]
template<typename TC , typename TD > A< TC, TD >::~A () inline
Definition at line 124 of file testCountedPtr.cpp.
  {
    --nb;
    trace.info() << "#" << nb << " A::~A(), a was " << a << std::endl;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
A() [5/7]
template<typename TC , typename TD > A< TC, TD >::A (int _a) inline
Definition at line 44 of file testCountedPtrOrPtr.cpp.
              : a( _a )
  {
    ++nb;
    trace.info() << "#" << nb << " A::A( int ), a is " << a << std::endl;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
A() [6/7]
template<typename TC , typename TD > A< TC, TD >::A (const A< TC, TD > & other) inline
Definition at line 49 of file testCountedPtrOrPtr.cpp.
                      : a( other.a )
  {
    ++nb;
    trace.info() << "#" << nb << " A::A( const A& ), a is " << a << std::endl;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
~A() [3/3]
template<typename TC , typename TD > A< TC, TD >::~A () inline
Definition at line 61 of file testCountedPtrOrPtr.cpp.
  {
    --nb;
    trace.info() << "#" << nb << " A::~A(), a was " << a << std::endl;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
A() [7/7]
template<typename TC , typename TD > A< TC, TD >::A (const C & c) inline
Definition at line 53 of file testPartialTemplateSpecialization.cpp.
{
  boost::ignore_unused_variable_warning( c );
  std::cout << "Generic" << std::endl;
}
Member Function Documentation
operator=() [1/3]
template<typename TC , typename TD > A & A< TC, TD >::operator= (const A< TC, TD > & other) inline
Definition at line 54 of file testCountedConstPtrOrConstPtr.cpp.
  {
    if ( this != &other )
      a = other.a;
    trace.info() << "#" << nb << " A::op=( const A& ), a is " << a << std::endl;
    return *this;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
operator=() [2/3]
template<typename TC , typename TD > A & A< TC, TD >::operator= (const A< TC, TD > & other) inline
Definition at line 117 of file testCountedPtr.cpp.
  {
    if ( this != &other )
      a = other.a;
    trace.info() << "#" << nb << " A::op=( const A& ), a is " << a << std::endl;
    return *this;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
operator=() [3/3]
template<typename TC , typename TD > A & A< TC, TD >::operator= (const A< TC, TD > & other) inline
Definition at line 54 of file testCountedPtrOrPtr.cpp.
  {
    if ( this != &other )
      a = other.a;
    trace.info() << "#" << nb << " A::op=( const A& ), a is " << a << std::endl;
    return *this;
  }
References A< TC, TD >::a, DGtal::Trace::info(), A< TC, TD >::nb, and DGtal::trace.
Field Documentation
a
template<typename TC , typename TD > int A< TC, TD >::a
Definition at line 67 of file testCountedConstPtrOrConstPtr.cpp.
Referenced by A< TC, TD >::A(), A< TC, TD >::A(), CompareToArithmetical(), A< TC, TD >::operator=(), and A< TC, TD >::~A().
nb
template<typename TC , typename TD > int A< TC, TD >::nb = 0 static
Definition at line 66 of file testCountedConstPtrOrConstPtr.cpp.
Referenced by A< TC, TD >::A(), A< TC, TD >::A(), A< TC, TD >::operator=(), testCountedConstPtrOrConstPtrMemory(), testCountedPtrMemory(), testCountedPtrOrPtrMemory(), and A< TC, TD >::~A().
The documentation for this class was generated from the following files:
testCountedConstPtrOrConstPtr.cpp
testPartialTemplateSpecialization.cpp
testCountedPtr.cpp
testCountedPtrOrPtr.cpp