DGtal: DiagonalPriority< CubicalComplex > Struct Template Reference
DiagonalPriority< CubicalComplex > Struct Template Reference
Public Types
typedef CubicalComplex::KSpace KSpace
typedef CubicalComplex::Point Point
typedef CubicalComplex::Cell Cell
typedef CubicalComplex::CellMapIterator CellMapIterator
Public Member Functions
DiagonalPriority (const CubicalComplex &complex)
bool operator() (const CellMapIterator &it1, const CellMapIterator &it2) const
Data Fields
const CubicalComplex & myComplex
Detailed Description
template<typename CubicalComplex>
struct DiagonalPriority< CubicalComplex >
The diagonal property induces that cells further away from the straight line (1,..,1)*x are removed first in a collapse operation. Could be used instead of giving values to each cell data.
Examples
topology/cubical-complex-collapse.cpp.
Definition at line 90 of file cubical-complex-collapse.cpp.
Member Typedef Documentation
Cell
template<typename CubicalComplex > typedef CubicalComplex::Cell DiagonalPriority< CubicalComplex >::Cell
Examples
topology/cubical-complex-collapse.cpp.
Definition at line 93 of file cubical-complex-collapse.cpp.
CellMapIterator
template<typename CubicalComplex > typedef CubicalComplex::CellMapIterator DiagonalPriority< CubicalComplex >::CellMapIterator
Examples
topology/cubical-complex-collapse.cpp.
Definition at line 94 of file cubical-complex-collapse.cpp.
KSpace
template<typename CubicalComplex > typedef CubicalComplex::KSpace DiagonalPriority< CubicalComplex >::KSpace
Examples
topology/cubical-complex-collapse.cpp.
Definition at line 91 of file cubical-complex-collapse.cpp.
Point
template<typename CubicalComplex > typedef CubicalComplex::Point DiagonalPriority< CubicalComplex >::Point
Examples
topology/cubical-complex-collapse.cpp.
Definition at line 92 of file cubical-complex-collapse.cpp.
Constructor & Destructor Documentation
DiagonalPriority()
template<typename CubicalComplex > DiagonalPriority< CubicalComplex >::DiagonalPriority (const CubicalComplex & complex) inline
Definition at line 96 of file cubical-complex-collapse.cpp.
: myComplex(complex) {}
Member Function Documentation
operator()()
template<typename CubicalComplex > bool DiagonalPriority< CubicalComplex >::operator() (const CellMapIterator & it1, const CellMapIterator & it2) const inline
Examples
topology/cubical-complex-collapse.cpp.
Definition at line 97 of file cubical-complex-collapse.cpp.
  {
    Point k1 = myComplex.space().uKCoords( it1->first );
    Point k2 = myComplex.space().uKCoords( it2->first );
    double d1 = Point::diagonal( 1 ).dot( k1 ) / sqrt( (double) KSpace::dimension );
    double d2 = Point::diagonal( 1 ).dot( k2 ) / sqrt( (double) KSpace::dimension );;
    RealPoint v1( k1[ 0 ] - d1 * k1[ 0 ], k1[ 1 ] - d1 * k1[ 1 ], k1[ 2 ] - d1 * k1[ 2 ] );
    RealPoint v2( k2[ 0 ] - d2 * k2[ 0 ], k2[ 1 ] - d2 * k2[ 1 ], k2[ 2 ] - d2 * k2[ 2 ] );
    double n1 = v1.dot( v1 );
    double n2 = v2.dot( v2 );
    return ( n1 < n2 ) || ( ( n1 == n2 ) && ( it1->first < it2->first ) );
  }
References DGtal::PointVector< dim, Integer >::diagonal(), DGtal::KhalimskySpaceND< dim, TInteger >::dimension, DGtal::PointVector< dim, TEuclideanRing, TContainer >::dot(), DiagonalPriority< CubicalComplex >::myComplex, and DGtal::CubicalComplex< TKSpace, TCellContainer >::space().
Field Documentation
myComplex
template<typename CubicalComplex > const CubicalComplex& DiagonalPriority< CubicalComplex >::myComplex
Examples
topology/cubical-complex-collapse.cpp.
Definition at line 110 of file cubical-complex-collapse.cpp.
Referenced by DiagonalPriority< CubicalComplex >::operator()().
The documentation for this struct was generated from the following file:
cubical-complex-collapse.cpp