DGtal: Fixture_complex_fig4 Struct Reference
Fixture_complex_fig4 Struct Reference
Public Types
using Point = DGtal::Z3i::Point
using Domain = DGtal::Z3i::Domain
using KSpace = DGtal::Z3i::KSpace
using FixtureDigitalSet = DGtal::DigitalSetByAssociativeContainer< DGtal::Z3i::Domain, std::unordered_set< typename DGtal::Z3i::Domain::Point > >
using FixtureMap = std::unordered_map< KSpace::Cell, CubicalCellData >
using FixtureComplex = DGtal::VoxelComplex< KSpace, FixtureMap >
Public Member Functions
Fixture_complex_fig4 ()
FixtureDigitalSet create_set ()
FixtureComplex & create_complex_from_set (const FixtureDigitalSet &input_set)
Data Fields
KSpace ks_fixture
FixtureComplex complex_fixture
Detailed Description
Definition at line 448 of file testVoxelComplex.cpp.
Member Typedef Documentation
Domain
using Fixture_complex_fig4::Domain = DGtal::Z3i::Domain
Definition at line 453 of file testVoxelComplex.cpp.
FixtureComplex
using Fixture_complex_fig4::FixtureComplex = DGtal::VoxelComplex<KSpace, FixtureMap>
Definition at line 460 of file testVoxelComplex.cpp.
FixtureDigitalSet
using Fixture_complex_fig4::FixtureDigitalSet = DGtal::DigitalSetByAssociativeContainer< DGtal::Z3i::Domain, std::unordered_set<typename DGtal::Z3i::Domain::Point> >
Definition at line 456 of file testVoxelComplex.cpp.
FixtureMap
using Fixture_complex_fig4::FixtureMap = std::unordered_map<KSpace::Cell, CubicalCellData>
Definition at line 459 of file testVoxelComplex.cpp.
KSpace
using Fixture_complex_fig4::KSpace = DGtal::Z3i::KSpace
Definition at line 454 of file testVoxelComplex.cpp.
Point
using Fixture_complex_fig4::Point = DGtal::Z3i::Point
Definition at line 452 of file testVoxelComplex.cpp.
Constructor & Destructor Documentation
Fixture_complex_fig4()
Fixture_complex_fig4::Fixture_complex_fig4 () inline
Definition at line 471 of file testVoxelComplex.cpp.
                           : complex_fixture(ks_fixture) {
        create_complex_from_set(create_set());
    }
References create_complex_from_set(), and create_set().
Member Function Documentation
create_complex_from_set()
FixtureComplex & Fixture_complex_fig4::create_complex_from_set (const FixtureDigitalSet & input_set) inline
Definition at line 515 of file testVoxelComplex.cpp.
{
        ks_fixture.init(input_set.domain().lowerBound(),
                        input_set.domain().upperBound(), true);
        complex_fixture = FixtureComplex(ks_fixture);
        complex_fixture.construct(input_set);
        return complex_fixture;
    }
References complex_fixture, DGtal::VoxelComplex< TKSpace, TCellContainer >::construct(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), ks_fixture, DGtal::HyperRectDomain< TSpace >::lowerBound(), and DGtal::HyperRectDomain< TSpace >::upperBound().
Referenced by Fixture_complex_fig4().
create_set()
FixtureDigitalSet Fixture_complex_fig4::create_set () inline
Definition at line 478 of file testVoxelComplex.cpp.
{
        using namespace DGtal;
        Point p1(-10, -10, -10);
        Point p2(10, 10, 10);
        Domain domain(p1, p2);
        // 12 voxels of fig4, centered in critical voxel
        FixtureDigitalSet fig4_set(domain);
        Point a1(0, 0, 0);
        fig4_set.insertNew(a1);
        Point a2(0, -1, 0);
        fig4_set.insertNew(a2);
        Point a3(1, -1, 0);
        fig4_set.insertNew(a3);
        Point c1(0, 1, -1);
        fig4_set.insertNew(c1);
        Point c2(1, 1, -1);
        fig4_set.insertNew(c2);
        Point c3(1, 2, -1);
        fig4_set.insertNew(c3);
        Point c4(0, 2, -1);
        fig4_set.insertNew(c4);
        Point b1(0, 2, 0);
        fig4_set.insertNew(b1);
        Point b2(-1, 3, 0);
        fig4_set.insertNew(b2);
        Point l1(1, 0, -2);
        fig4_set.insertNew(l1);
        Point l2(2, 0, -2);
        fig4_set.insertNew(l2);
        Point r1(1, 3, -2);
        fig4_set.insertNew(r1);
        return fig4_set;
    }
References domain, and DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::insertNew().
Referenced by Fixture_complex_fig4().
Field Documentation
complex_fixture
FixtureComplex Fixture_complex_fig4::complex_fixture
Definition at line 465 of file testVoxelComplex.cpp.
Referenced by create_complex_from_set().
ks_fixture
KSpace Fixture_complex_fig4::ks_fixture
Definition at line 464 of file testVoxelComplex.cpp.
Referenced by create_complex_from_set().
The documentation for this struct was generated from the following file:
testVoxelComplex.cpp