DGtal: Fixture_complex_diamond Struct Reference
Fixture_complex_diamond Struct Reference
Public Types
using Point = DGtal::Z3i::Point
using Domain = DGtal::Z3i::Domain
using KSpace = DGtal::Z3i::KSpace
using FixtureDigitalTopology = DGtal::Z3i::DT26_6
using FixtureDigitalSet = DGtal::DigitalSetByAssociativeContainer< DGtal::Z3i::Domain, std::unordered_set< typename DGtal::Z3i::Domain::Point > >
using FixtureComplex = DGtal::VoxelComplex< KSpace >
Public Member Functions
Fixture_complex_diamond ()
FixtureDigitalSet create_set ()
FixtureComplex & create_complex_from_set (const FixtureDigitalSet &input_set)
Data Fields
KSpace ks_fixture
FixtureComplex complex_fixture
Detailed Description
Definition at line 58 of file testVoxelComplex.cpp.
Member Typedef Documentation
Domain
using Fixture_complex_diamond::Domain = DGtal::Z3i::Domain
Definition at line 63 of file testVoxelComplex.cpp.
FixtureComplex
using Fixture_complex_diamond::FixtureComplex = DGtal::VoxelComplex<KSpace>
Definition at line 70 of file testVoxelComplex.cpp.
FixtureDigitalSet
using Fixture_complex_diamond::FixtureDigitalSet = DGtal::DigitalSetByAssociativeContainer< DGtal::Z3i::Domain, std::unordered_set<typename DGtal::Z3i::Domain::Point> >
Definition at line 67 of file testVoxelComplex.cpp.
FixtureDigitalTopology
using Fixture_complex_diamond::FixtureDigitalTopology = DGtal::Z3i::DT26_6
Definition at line 66 of file testVoxelComplex.cpp.
KSpace
using Fixture_complex_diamond::KSpace = DGtal::Z3i::KSpace
Definition at line 64 of file testVoxelComplex.cpp.
Point
using Fixture_complex_diamond::Point = DGtal::Z3i::Point
Definition at line 62 of file testVoxelComplex.cpp.
Constructor & Destructor Documentation
Fixture_complex_diamond()
Fixture_complex_diamond::Fixture_complex_diamond () inline
Definition at line 76 of file testVoxelComplex.cpp.
                              :
        complex_fixture(ks_fixture) {
            create_complex_from_set(create_set());
    }
References create_complex_from_set(), and create_set().
Member Function Documentation
create_complex_from_set()
FixtureComplex & Fixture_complex_diamond::create_complex_from_set (const FixtureDigitalSet & input_set) inline
Definition at line 110 of file testVoxelComplex.cpp.
{
        ks_fixture.init(input_set.domain().lowerBound(),
                        input_set.domain().upperBound(), true);
        complex_fixture = FixtureComplex(ks_fixture);
        complex_fixture.construct(input_set);
        return complex_fixture;
    }
References complex_fixture, DGtal::VoxelComplex< TKSpace, TCellContainer >::construct(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::domain(), DGtal::KhalimskySpaceND< dim, TInteger >::init(), ks_fixture, DGtal::HyperRectDomain< TSpace >::lowerBound(), and DGtal::HyperRectDomain< TSpace >::upperBound().
Referenced by Fixture_complex_diamond().
create_set()
FixtureDigitalSet Fixture_complex_diamond::create_set () inline
Definition at line 90 of file testVoxelComplex.cpp.
{
        using namespace DGtal;
        // trace.beginBlock ( "Create Fixture_object_diamond" );
        Point p1(-10, -10, -10);
        Point p2(10, 10, 10);
        Domain domain(p1, p2);
        Point c(0, 0, 0);
        // diamond of radius 4
        FixtureDigitalSet set_fixture(domain);
        for (auto it = domain.begin(); it != domain.end(); ++it) {
            if ((*it - c).norm1() <= 3)
                set_fixture.insertNew(*it);
        }
        set_fixture.erase(c);
        return set_fixture;
    }
References DGtal::HyperRectDomain< TSpace >::begin(), domain, DGtal::HyperRectDomain< TSpace >::end(), DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::erase(), and DGtal::DigitalSetByAssociativeContainer< TDomain, TContainer >::insertNew().
Referenced by Fixture_complex_diamond().
Field Documentation
complex_fixture
FixtureComplex Fixture_complex_diamond::complex_fixture
Definition at line 84 of file testVoxelComplex.cpp.
Referenced by create_complex_from_set().
ks_fixture
KSpace Fixture_complex_diamond::ks_fixture
Definition at line 83 of file testVoxelComplex.cpp.
Referenced by create_complex_from_set().
The documentation for this struct was generated from the following file:
testVoxelComplex.cpp