var searchData=
[
  ['i_20models_20of_20graph_0',['Topology Concepts and Models (part I, models of graph)',['../packageTopologyConcepts1.html',1,'packageTopology']]],
  ['ii_20digital_20surfaces_20surfel_20predicates_1',['Topology Concepts and Models (part II, digital surfaces, surfel predicates)',['../packageTopologyConcepts2.html',1,'packageTopology']]],
  ['image_20and_20digital_20object_20import_20export_2',['Image and digital object import/export',['../moduleIO.html',1,'packageIO']]],
  ['image_20concepts_3',['Main Image Concepts',['../packageImageConcepts.html',1,'packageImage']]],
  ['image_20imageadapter_3a_20some_20simple_20image_20manipulations_4',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['image_20package_5',['Image package',['../packageImage.html',1,'index']]],
  ['image_20region_20distance_20transformation_6',['Tutorial &quot;Image -&gt; Region -&gt; Distance Transformation&quot;',['../tutoImageRegionDT.html',1,'packageTutorials']]],
  ['image_20region_20grid_20curve_20extracting_20level_20set_20boundary_20from_20image_7',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt;  Extracting level set boundary from Image&quot;',['../tutoImageGridCurveExtraction.html',1,'packageTutorials']]],
  ['image_20region_20grid_20curve_20length_20estimation_8',['Tutorial &quot;Image -&gt; Region -&gt; Grid curve -&gt; Length estimation&quot;',['../tutoImageGridCurveEstimator.html',1,'packageTutorials']]],
  ['image_20region_20volume_203dvolviewer_20_3a_20a_20simple_203d_20volume_20viewer_20in_20less_20than_2050_20lines_9',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['../tutoImageGridVolume3dVolViewer.html',1,'packageTutorials']]],
  ['imageadapter_3a_20some_20simple_20image_20manipulations_10',['Tutorial &quot;Image -&gt; ImageAdapter: some simple image manipulations&quot;',['../tutoImageManipulations.html',1,'packageTutorials']]],
  ['images_11',['Images',['../moduleImages.html',1,'packageImage']]],
  ['images_20in_20dgtal_12',['Handle large images in DGtal',['../moduleBigImages.html',1,'packageImage']]],
  ['implementation_20of_20geometric_20predicates_13',['Implementation of geometric predicates',['../moduleGeometricPredicates.html',1,'packageGeometry']]],
  ['import_20export_14',['Image and digital object import/export',['../moduleIO.html',1,'packageIO']]],
  ['in_20arbitrary_20dimension_20for_20convex_20hull_20and_20delaunay_20cell_20complex_20computation_15',['QuickHull algorithm in arbitrary dimension for convex hull and Delaunay cell complex computation',['../moduleQuickHull.html',1,'moduleAffineGeometry']]],
  ['in_20dgtal_16',['in dgtal',['../moduleFAQGit.html',1,'Git/Github source code management in DGtal'],['../moduleBigImages.html',1,'Handle large images in DGtal'],['../moduleFunctors.html',1,'Using functions, functors and lambdas in DGtal']]],
  ['in_20dgtal_20using_20catch_17',['Unit test in DGtal using Catch',['../moduleCatch.html',1,'packageDev']]],
  ['in_20digital_20spaces_18',['Sets of points in digital spaces',['../moduleDigitalSets.html',1,'packageKernel']]],
  ['in_20heat_20using_20discrete_20polygonal_20calculus_19',['Geodesics In Heat using discrete polygonal calculus',['../moduleGeodesicsInHeat.html',1,'packageDEC']]],
  ['in_20less_20than_2050_20lines_20',['Tutorial &quot;Image -&gt; Region -&gt; Volume -&gt;  3dVolViewer : a simple 3D volume viewer in less than 50 lines&quot;',['../tutoImageGridVolume3dVolViewer.html',1,'packageTutorials']]],
  ['in_20my_20own_20project_21',['How to use DGtal in my own project ?',['../moduleHowToUseDGtal.html',1,'packageIntroduction']]],
  ['in_20r3_22',['Surface mesh data structure for representing manifold or non-manifold polygonal surfaces in R3',['../moduleSurfaceMesh.html',1,'packageShapes']]],
  ['in_20the_20digital_20plane_20zxz_20convex_20polygons_20with_20vertices_20at_20integer_20coordinates_23',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['in_20the_20plane_24',['Convex hull and alpha-shape in the plane',['../moduleHull2D.html',1,'packageGeometry']]],
  ['incidence_25',['Cellular grid space and topology, unoriented and oriented cells, incidence',['../moduleCellularTopology.html',1,'packageTopology']]],
  ['integer_20computations_26',['Integer computations',['../moduleIntegerComputations.html',1,'packageArithmetic']]],
  ['integer_20concepts_27',['Number and Integer Concepts',['../moduleNumber.html',1,'packageKernel']]],
  ['integer_20coordinates_28',['Lattice polytopes in the digital plane ZxZ (convex polygons with vertices at integer coordinates)',['../moduleLatticePolytope2D.html',1,'packageArithmetic']]],
  ['integral_20invariant_20curvature_20estimator_202d_203d_29',['Integral invariant curvature estimator 2D/3D',['../moduleIntegralInvariant.html',1,'packageGeometry']]],
  ['interfacing_20with_20boost_3a_3agraph_20library_30',['Interfacing with boost::graph library',['../moduleBoostGraphWrapping.html',1,'packageGraph']]],
  ['into_20m_20dimensional_20space_31',['Embedding n-dimensional DEC structures into m-dimensional space',['../moduleDECEmbedding.html',1,'packageDEC']]],
  ['introduction_32',['Introduction',['../moduleIntroduction.html',1,'packageIntroduction']]],
  ['invariant_20curvature_20estimator_202d_203d_33',['Integral invariant curvature estimator 2D/3D',['../moduleIntegralInvariant.html',1,'packageGeometry']]],
  ['io_20package_34',['IO package',['../packageIO.html',1,'index']]],
  ['irreducible_20fraction_20continued_20fractions_35',['Irreducible fraction, continued fractions',['../moduleIrreducibleFraction.html',1,'packageArithmetic']]],
  ['iterators_20and_20ranges_36',['Iterators and ranges',['../moduleIteratorsRanges.html',1,'packageBase']]]
];
